define bgm_title = "assets/audio/bgm/Mockup of a Repeating Theme for Finding Joy.ogg"
define bgm_title_reversed = "assets/audio/bgm/Mockup of a Repeating Theme for Finding Joy (reversed).ogg"
define bgm_office = "assets/audio/bgm/audio_office.ogg"
define bgm_metal = "assets/audio/bgm/audio_metal.ogg"
define bgm_fireplace = "assets/audio/bgm/audio_fireplace.ogg"
